apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkus-test-result-2
  janus-idp.io/tekton: quarkus-test-result-2
  backstage.io/kubernetes-id: quarkus-test-result-2
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: quarkus-test-result-2
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
